### PR TITLE
Updated website

### PR DESCRIPTION
**Pull request by zuhairtaha**

### CODE REVIEW

**Comment by kevinsimper** [comment]
Hi @zuhairtaha, since this deletes everything, it is not a good pull request for this repo since it is basically a new website :)

A PR works best if it is a small chance that improves something :)

Also you didn't include any description or have added any comments :)

What do you think?

**Comment by zuhairtaha** [comment]
Hi @kevinsimper 
Benjamin wanted to make this pull request. I was expected to stop working on this project, but I will continue working on it. 
I don't know what comments should I add. I think anyone know react and next.js can understand the project struture. 
However, I added discription at readme file: 
[README](https://github.com/zuhairtaha/hackyourfuture.dk/blob/master/README.md)

**Comment by kevinsimper** [comment]
Can you split this up to smaller pull requests? It is not that great to review 12000 lines of edits :)

**Comment by kevinsimper** [comment]
This PR has to be closed as it is not manageable to merge 13.000 lines of code. You are free to still ask question on this PR if you have any :)

**Comment by zuhairtaha** [comment]
I think so. the changes are not few. I followed with the same struture but in fact it is new one. So I think It will be better to deploy the new one. Also I'm still working with it. It is not finished yet

**Pull request closed without merging**
