### PR TITLE
Newsletter

### PR DESCRIPTION
**Pull request by abdualrhman**

### CODE REVIEW

**Comment by kevinsimper** [comment]
@abdualrhman Thanks for making a pull request, can you provide a screenshot of how it looks? 😄

**Comment by abdualrhman** [comment]
@kevinsimper 
untitled

**Comment by jawkha** [comment]
@abdualrhman have you figured out how to align the header and the input field with the description at the center to make the whole block look nice and centered?

**Comment by abdualrhman** [comment]
@jawkha thanks for the feedback 😀, should I also remove the newsletter from the footer?

**Comment by jawkha** [comment]
Here's a hacky version to make it work. You can probably clean up the styling further.
``` js
export default () => (
  <form
    action="https://hackyourfuture.us18.list-manage.com/subscribe/post?u=3d0c0055da1f780c58ef56540&amp;id=e9cde1fe9a"
    method="post"
  >
    <style jsx>
      {`
        .newsletter {
          display: flex;
          flex-direction: column;
        }

        .email {
          font-size: 1rem;
          padding: 8px;
          width: 240px;
        }

        .form-submit {
          margin: 0 auto 10px;
        }

        .submit {
          font-size: 1rem;
          border: 0;
          background: #2ecc40;
          color: white;
          padding: 10px;
        }

        .header {
          margin: 0 auto 10px;
        }
        
        .description {
          font-size: 1rem;
          max-width: 300px;
          text-align: center;
          margin: 0 auto 10px;
        }
      `}
    </style>
    <div className="newsletter">
      <h3 className="header">Sign up for our newsletter!</h3>
      <div className="description">
        We will send a monthly update on the project and what new cool things we
        are doing at HackYourFuture.
    </div>
      <div className="form-submit">
        <input
          type="email"
          name="EMAIL"
          className="email"
          placeholder="you@example.com"
        />
        <input
          type="submit"
          value="Subscribe"
          name="subscribe"
          className="submit"
        />
      </div>
    </div>
  </form>
)
```

**Comment by jawkha** [comment]
screen shot 2018-06-13 at 20 56 05

**Comment by kevinsimper** [comment]
> @jawkha thanks for the feedback 😀, should I also remove the newsletter from the footer?

I think it should both be in the footer and on the page /newsletter

**Comment by kevinsimper** [comment]
The component in the footer and the component on the page should not be the same. The one in the footer will always be smaller, smaller input fields, shorter text. So it does not make sense in this case to reuse the component since the logic is not more than a form.

If there should be something share I think you can make a file that contains the variables so they are not duplicated.

The content looks prettier if it is not align center if there will be more content.

**Comment by kevinsimper** [comment]
Another thing to consider, what if the footer change and you want to change the newsletter signup in the footer, suddenly you are changing another page as well without knowing or it becomes 10x more difficult.

**Comment by abdualrhman** [comment]
untitled

**Comment by kevinsimper** [comment]
@abdualrhman Nice, that looks really good! Can you run the `npm run fix-lint`?

**Comment by abdualrhman** [comment]
@kevinsimper yes, I can

**Pull request merged**
